version: '3'
services:
  strongbox-web-integration-tests-choco:
    image: strongboxci/alpine:jdk8-mvn3.6-mono5-nuget3.4-choco0.10
    volumes:
      - $HOME/.m2/repository:/home/jenkins/.m2/repository
      - ../:/workspace
    working_dir: /workspace/choco
    command: mvn clean install
