version: '3'
services:
  strongbox-web-integration-tests-npm:
    image: strongboxci/alpine:jdk8-mvn3.6-node12
    volumes:
      - $HOME/.m2/repository:/home/jenkins/.m2/repository
      - ../:/workspace
    working_dir: /workspace/npm
    command: mvn clean install -U
